#!/bin/bash
set -euo pipefail

INTERFACE=$(ip route | awk '/default via/ { print $5; }')

pacman -Sy wget --noconfirm
wget https://raw.githubusercontent.com/flatcar-linux/init/flatcar-master/bin/flatcar-install
chmod +x flatcar-install
./flatcar-install -s -C alpha
mkdir /tmp/b
mount /dev/sda1 /tmp/b
cd /tmp/b/flatcar/grub/
cp grub.cfg.tar grub.cfg.tar.orig
tar xvf grub.cfg.tar --no-same-owner

MAC=$(ip a show dev $INTERFACE | awk '/link\/ether/ { print $2; }')
sed -i "s/linux\$suf \$gptprio_kernel \$gptprio_cmdline \$linux_cmdline$/linux\$suf \$gptprio_kernel \$gptprio_cmdline flatcar.config.url='http:\/\/matchbox.lan:8080\/ignition?uuid=123\&mac=${MAC}'/" grub.cfg
tar cvf grub.cfg.tar grub.cfg --owner=1000
